# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl: ""
url: https://wjrye.github.io
date_format: "ordinal"
title: Wang Jiang
subtitle: Young Forever
description: "Pain is inevitable. Suffering is optional."
keywords: SoftwareDeveloper
timezone: Asia/Beijing
encoding: "utf-8"
# 页面左下角显示的年份
since: 2015
# 源码仓库，请替换成自己的
repository: WJRye/wjrye.github.io
# 对 css 和 js 资源的 cdn 加速配置
cdn:
    jsdelivr:
        enabled: false
# 可选组件配置
components:
    # 分享
    # weibo,qq,wechat,douban,qzone,linkedin,facebook,twitter
    share:
        enabled: true
        hide-platforms:
    # 不蒜子访问统计
    busuanzi:
        enabled: false
        start_date: 2024-05-01
    # My Popular Repositories
    side_bar_repo:
        enabled: false
        limit: 5
    # 文章字数统计
    word_count:
        enabled: true
    # 页面右上角，以及「关于」页面的二维码
    # 修改图片请替换 assets/images/qrcode.jpg
    qrcode:
        enabled: false
        image_alt: 划水健儿
    # 维基索引页使用哪种视图，支持 列表（list）/分类（cate）
    wiki:
        view: cate
    # 图片灯箱效果功能
    fancybox:
        enabled: false
# 压缩页面内容
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
# 代码高亮风格，支持的 theme 列表见 https://github.com/mzlogin/rouge-themes
highlight_theme: github

# ---------------- #
#      Author      #
# ---------------- #
author: Wang Jiang
organization: 
organization_url: 
github_username: WJRye
location: Shanghai, China
email: wangjiang7747@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /archives/
    label: 归档
    mobile-hidden: true

  -
    href: /open-source/
    label: 开源
    mobile-hidden: true

  -
    href: /fragments/
    label: 片段

  -
    href: /wiki/
    label: 知识

  -
    href: /links/
    label: 家庭
    mobile-hidden: true

  -
    href: /like/
    label: 喜好

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      INDEX       #
# ---------------- #
index:
    banner:
        # 首页 banner 区文字颜色
        color: "#FFFFFF"
        # 首页导航栏文字颜色
        nav-color: "#FFFFFF"
        # 首页 banner 区背景颜色
        background-color: "#003366"
        # 首页 banner 区背景图片
        # background-image: "/assets/images/octicons-bg.png"
        # background-repeat: "no-repeat"
        # background-size: "cover"

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
markdown_ext:  "markdown,mkdown,mkdn,mkd,md"
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    fragments:
        output: true
        permalink: /fragment/:path/

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk, utterances, beaudar, giscus
comments_provider: giscus
# giscus 配置参考：https://giscus.app/zh-CN
giscus:
    repo: WJRye/wjrye.github.io
    repo-id: R_kgDOLOA6fQ
    category: Announcements
    category-id: DIC_kwDOLOA6fc4CgVNF

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#      Google      #
# ---------------- #
google:
    analytics_id: # G-20FLEG5Q2W
    adsense:
        enabled: false
        footer: false
        sidebar: false
        sidebar-detail: false
        content_header: false
        content_footer: false
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
