# Site settings
title: WangJiang
description: ""
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wjrye.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
